In [30]:
from data.raw_loader import *


In [35]:
sm_data= np.arange(1,10).reshape((-1,1))
bsm_data= 10*sm_data

np.save( 'sm.npy',sm_data)
np.save( 'bsm.npy',bsm_data)

sm_files = ['sm.npy']
bsm_files = ['bsm.npy']

build(sm_files, bsm_files, '.', normalize=False)


In [36]:
print(np.load('sm.npy', allow_pickle=True))
print(np.load('bsm.npy', allow_pickle=True))


[[1]
 [2]
 [3]
 [4]
 [5]
 [6]
 [7]
 [8]
 [9]]
[[10]
 [20]
 [30]
 [40]
 [50]
 [60]
 [70]
 [80]
 [90]]


In [37]:
data = np.load('train_supervised.npy', allow_pickle=True).item()
print(data['x'].shape)
print(data['y'].shape)

print(data['x'])
print(data['y'])

(8, 1)
(8,)
[[80]
 [20]
 [ 9]
 [ 2]
 [ 8]
 [70]
 [50]
 [ 6]]
[1. 1. 0. 0. 0. 1. 1. 0.]


In [38]:
data = np.load('train_sm_only.npy', allow_pickle=True)
print(data.shape)
print(data)

(4, 1)
[[2]
 [9]
 [6]
 [8]]
